// Comprehensive travel dataset: every country in the world with its currency
// and a handful of major cities. Used to power the country selector, the
// city autocomplete, and the automatic currency derivation.
//
// Covers all 193 UN member states plus several commonly-traveled territories
// (Taiwan, Hong Kong, Macau, Puerto Rico, Vatican City, Kosovo, Palestine,
// Bermuda, Cayman Islands, Greenland, New Caledonia, French Polynesia, etc.).

export interface CountryEntry {
  name: string;
  iso2: string;
  currency: string; // ISO 4217 code
  cities: string[];
}

// Organized alphabetically by country name.
export const COUNTRY_DATA: CountryEntry[] = [
  { name: "Afghanistan", iso2: "AF", currency: "AFN", cities: ["Kabul", "Herat", "Kandahar", "Mazar-i-Sharif"] },
  { name: "Albania", iso2: "AL", currency: "ALL", cities: ["Tirana", "Durrës", "Vlorë", "Shkodër"] },
  { name: "Algeria", iso2: "DZ", currency: "DZD", cities: ["Algiers", "Oran", "Constantine", "Annaba"] },
  { name: "Andorra", iso2: "AD", currency: "EUR", cities: ["Andorra la Vella", "Escaldes-Engordany", "Encamp"] },
  { name: "Angola", iso2: "AO", currency: "AOA", cities: ["Luanda", "Huambo", "Benguela", "Lobito"] },
  { name: "Antigua and Barbuda", iso2: "AG", currency: "XCD", cities: ["St. John's", "All Saints", "Codrington"] },
  { name: "Argentina", iso2: "AR", currency: "ARS", cities: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza"] },
  { name: "Armenia", iso2: "AM", currency: "AMD", cities: ["Yerevan", "Gyumri", "Vanadzor", "Dilijan"] },
  { name: "Australia", iso2: "AU", currency: "AUD", cities: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"] },
  { name: "Austria", iso2: "AT", currency: "EUR", cities: ["Vienna", "Salzburg", "Innsbruck", "Graz"] },
  { name: "Azerbaijan", iso2: "AZ", currency: "AZN", cities: ["Baku", "Ganja", "Sheki", "Lankaran"] },
  { name: "Bahamas", iso2: "BS", currency: "BSD", cities: ["Nassau", "Freeport", "West End"] },
  { name: "Bahrain", iso2: "BH", currency: "BHD", cities: ["Manama", "Riffa", "Muharraq"] },
  { name: "Bangladesh", iso2: "BD", currency: "BDT", cities: ["Dhaka", "Chittagong", "Khulna", "Sylhet"] },
  { name: "Barbados", iso2: "BB", currency: "BBD", cities: ["Bridgetown", "Speightstown", "Oistins"] },
  { name: "Belarus", iso2: "BY", currency: "BYN", cities: ["Minsk", "Brest", "Gomel", "Vitebsk"] },
  { name: "Belgium", iso2: "BE", currency: "EUR", cities: ["Brussels", "Bruges", "Antwerp", "Ghent"] },
  { name: "Belize", iso2: "BZ", currency: "BZD", cities: ["Belmopan", "Belize City", "San Ignacio"] },
  { name: "Benin", iso2: "BJ", currency: "XOF", cities: ["Porto-Novo", "Cotonou", "Parakou"] },
  { name: "Bermuda", iso2: "BM", currency: "BMD", cities: ["Hamilton", "St. George's"] },
  { name: "Bhutan", iso2: "BT", currency: "BTN", cities: ["Thimphu", "Paro", "Punakha"] },
  { name: "Bolivia", iso2: "BO", currency: "BOB", cities: ["La Paz", "Sucre", "Santa Cruz", "Cochabamba"] },
  { name: "Bosnia and Herzegovina", iso2: "BA", currency: "BAM", cities: ["Sarajevo", "Mostar", "Banja Luka"] },
  { name: "Botswana", iso2: "BW", currency: "BWP", cities: ["Gaborone", "Francistown", "Maun"] },
  { name: "Brazil", iso2: "BR", currency: "BRL", cities: ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador", "Recife"] },
  { name: "Brunei", iso2: "BN", currency: "BND", cities: ["Bandar Seri Begawan", "Kuala Belait"] },
  { name: "Bulgaria", iso2: "BG", currency: "BGN", cities: ["Sofia", "Plovdiv", "Varna", "Burgas"] },
  { name: "Burkina Faso", iso2: "BF", currency: "XOF", cities: ["Ouagadougou", "Bobo-Dioulasso", "Koudougou"] },
  { name: "Burundi", iso2: "BI", currency: "BIF", cities: ["Gitega", "Bujumbura"] },
  { name: "Cabo Verde", iso2: "CV", currency: "CVE", cities: ["Praia", "Mindelo", "Assomada"] },
  { name: "Cambodia", iso2: "KH", currency: "KHR", cities: ["Phnom Penh", "Siem Reap", "Battambang"] },
  { name: "Cameroon", iso2: "CM", currency: "XAF", cities: ["Yaoundé", "Douala", "Bamenda", "Bafoussam"] },
  { name: "Canada", iso2: "CA", currency: "CAD", cities: ["Toronto", "Vancouver", "Montreal", "Ottawa", "Calgary", "Quebec City"] },
  { name: "Cayman Islands", iso2: "KY", currency: "KYD", cities: ["George Town", "West Bay", "Bodden Town"] },
  { name: "Central African Republic", iso2: "CF", currency: "XAF", cities: ["Bangui", "Bimbo", "Bouar"] },
  { name: "Chad", iso2: "TD", currency: "XAF", cities: ["N'Djamena", "Moundou", "Sarh"] },
  { name: "Chile", iso2: "CL", currency: "CLP", cities: ["Santiago", "Valparaíso", "Viña del Mar", "Punta Arenas"] },
  { name: "China", iso2: "CN", currency: "CNY", cities: ["Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Chengdu", "Xi'an"] },
  { name: "Colombia", iso2: "CO", currency: "COP", cities: ["Bogotá", "Medellín", "Cali", "Cartagena"] },
  { name: "Comoros", iso2: "KM", currency: "KMF", cities: ["Moroni", "Mutsamudu", "Fomboni"] },
  { name: "Congo, Democratic Republic of the", iso2: "CD", currency: "CDF", cities: ["Kinshasa", "Lubumbashi", "Goma", "Bukavu"] },
  { name: "Congo, Republic of the", iso2: "CG", currency: "XAF", cities: ["Brazzaville", "Pointe-Noire", "Dolisie"] },
  { name: "Costa Rica", iso2: "CR", currency: "CRC", cities: ["San José", "Alajuela", "Heredia", "Liberia"] },
  { name: "Croatia", iso2: "HR", currency: "EUR", cities: ["Zagreb", "Dubrovnik", "Split", "Rovinj"] },
  { name: "Cuba", iso2: "CU", currency: "CUP", cities: ["Havana", "Santiago de Cuba", "Camagüey", "Varadero"] },
  { name: "Cyprus", iso2: "CY", currency: "EUR", cities: ["Nicosia", "Limassol", "Larnaca", "Paphos"] },
  { name: "Czech Republic", iso2: "CZ", currency: "CZK", cities: ["Prague", "Brno", "Ostrava", "Český Krumlov"] },
  { name: "Denmark", iso2: "DK", currency: "DKK", cities: ["Copenhagen", "Aarhus", "Odense", "Aalborg"] },
  { name: "Djibouti", iso2: "DJ", currency: "DJF", cities: ["Djibouti City", "Ali Sabieh", "Tadjoura"] },
  { name: "Dominica", iso2: "DM", currency: "XCD", cities: ["Roseau", "Portsmouth", "Marigot"] },
  { name: "Dominican Republic", iso2: "DO", currency: "DOP", cities: ["Santo Domingo", "Santiago", "Punta Cana", "Puerto Plata"] },
  { name: "Ecuador", iso2: "EC", currency: "USD", cities: ["Quito", "Guayaquil", "Cuenca", "Baños"] },
  { name: "Egypt", iso2: "EG", currency: "EGP", cities: ["Cairo", "Alexandria", "Luxor", "Aswan", "Giza"] },
  { name: "El Salvador", iso2: "SV", currency: "USD", cities: ["San Salvador", "Santa Ana", "San Miguel"] },
  { name: "Equatorial Guinea", iso2: "GQ", currency: "XAF", cities: ["Malabo", "Bata", "Ebebiyin"] },
  { name: "Eritrea", iso2: "ER", currency: "ERN", cities: ["Asmara", "Keren", "Assab"] },
  { name: "Estonia", iso2: "EE", currency: "EUR", cities: ["Tallinn", "Tartu", "Pärnu", "Narva"] },
  { name: "Eswatini", iso2: "SZ", currency: "SZL", cities: ["Mbabane", "Manzini", "Lobamba"] },
  { name: "Ethiopia", iso2: "ET", currency: "ETB", cities: ["Addis Ababa", "Gondar", "Lalibela", "Bahir Dar"] },
  { name: "Fiji", iso2: "FJ", currency: "FJD", cities: ["Suva", "Nadi", "Lautoka"] },
  { name: "Finland", iso2: "FI", currency: "EUR", cities: ["Helsinki", "Tampere", "Turku", "Rovaniemi"] },
  { name: "France", iso2: "FR", currency: "EUR", cities: ["Paris", "Nice", "Lyon", "Marseille", "Bordeaux", "Cannes"] },
  { name: "French Polynesia", iso2: "PF", currency: "XPF", cities: ["Papeete", "Faaa", "Punaauia"] },
  { name: "Gabon", iso2: "GA", currency: "XAF", cities: ["Libreville", "Port-Gentil", "Franceville"] },
  { name: "Gambia", iso2: "GM", currency: "GMD", cities: ["Banjul", "Serrekunda", "Brikama"] },
  { name: "Georgia", iso2: "GE", currency: "GEL", cities: ["Tbilisi", "Batumi", "Kutaisi", "Mestia"] },
  { name: "Germany", iso2: "DE", currency: "EUR", cities: ["Berlin", "Munich", "Hamburg", "Cologne", "Frankfurt", "Dresden"] },
  { name: "Ghana", iso2: "GH", currency: "GHS", cities: ["Accra", "Kumasi", "Tamale", "Cape Coast"] },
  { name: "Greece", iso2: "GR", currency: "EUR", cities: ["Athens", "Thessaloniki", "Santorini", "Mykonos", "Crete"] },
  { name: "Greenland", iso2: "GL", currency: "DKK", cities: ["Nuuk", "Sisimiut", "Ilulissat"] },
  { name: "Grenada", iso2: "GD", currency: "XCD", cities: ["St. George's", "Gouyave", "Grenville"] },
  { name: "Guatemala", iso2: "GT", currency: "GTQ", cities: ["Guatemala City", "Antigua Guatemala", "Quetzaltenango", "Flores"] },
  { name: "Guinea", iso2: "GN", currency: "GNF", cities: ["Conakry", "Kankan", "Kindia"] },
  { name: "Guinea-Bissau", iso2: "GW", currency: "XOF", cities: ["Bissau", "Bafatá", "Gabú"] },
  { name: "Guyana", iso2: "GY", currency: "GYD", cities: ["Georgetown", "Linden", "New Amsterdam"] },
  { name: "Haiti", iso2: "HT", currency: "HTG", cities: ["Port-au-Prince", "Cap-Haïtien", "Jacmel"] },
  { name: "Honduras", iso2: "HN", currency: "HNL", cities: ["Tegucigalpa", "San Pedro Sula", "La Ceiba", "Roatán"] },
  { name: "Hong Kong", iso2: "HK", currency: "HKD", cities: ["Hong Kong Island", "Kowloon", "Tsim Sha Tsui"] },
  { name: "Hungary", iso2: "HU", currency: "HUF", cities: ["Budapest", "Debrecen", "Szeged", "Eger"] },
  { name: "Iceland", iso2: "IS", currency: "ISK", cities: ["Reykjavík", "Akureyri", "Keflavík", "Vík"] },
  { name: "India", iso2: "IN", currency: "INR", cities: ["Mumbai", "Delhi", "Bangalore", "Jaipur", "Goa", "Kerala", "Chennai", "Kolkata", "Agra", "Varanasi"] },
  { name: "Indonesia", iso2: "ID", currency: "IDR", cities: ["Bali", "Jakarta", "Yogyakarta", "Surabaya", "Ubud"] },
  { name: "Iran", iso2: "IR", currency: "IRR", cities: ["Tehran", "Isfahan", "Shiraz", "Yazd"] },
  { name: "Iraq", iso2: "IQ", currency: "IQD", cities: ["Baghdad", "Basra", "Erbil", "Mosul"] },
  { name: "Ireland", iso2: "IE", currency: "EUR", cities: ["Dublin", "Cork", "Galway", "Killarney"] },
  { name: "Israel", iso2: "IL", currency: "ILS", cities: ["Jerusalem", "Tel Aviv", "Haifa", "Eilat"] },
  { name: "Italy", iso2: "IT", currency: "EUR", cities: ["Rome", "Venice", "Florence", "Milan", "Naples", "Amalfi", "Cinque Terre"] },
  { name: "Jamaica", iso2: "JM", currency: "JMD", cities: ["Kingston", "Montego Bay", "Negril", "Ocho Rios"] },
  { name: "Japan", iso2: "JP", currency: "JPY", cities: ["Tokyo", "Kyoto", "Osaka", "Hiroshima", "Sapporo", "Nara"] },
  { name: "Jordan", iso2: "JO", currency: "JOD", cities: ["Amman", "Petra", "Aqaba", "Wadi Musa"] },
  { name: "Kazakhstan", iso2: "KZ", currency: "KZT", cities: ["Almaty", "Astana", "Shymkent", "Turkestan"] },
  { name: "Kenya", iso2: "KE", currency: "KES", cities: ["Nairobi", "Mombasa", "Kisumu", "Maasai Mara"] },
  { name: "Kiribati", iso2: "KI", currency: "AUD", cities: ["Tarawa", "Bairiki", "Bikenibeu"] },
  { name: "Kosovo", iso2: "XK", currency: "EUR", cities: ["Pristina", "Prizren", "Peja", "Gjakova"] },
  { name: "Kuwait", iso2: "KW", currency: "KWD", cities: ["Kuwait City", "Hawalli", "Salmiya"] },
  { name: "Kyrgyzstan", iso2: "KG", currency: "KGS", cities: ["Bishkek", "Osh", "Karakol"] },
  { name: "Laos", iso2: "LA", currency: "LAK", cities: ["Vientiane", "Luang Prabang", "Vang Vieng", "Pakse"] },
  { name: "Latvia", iso2: "LV", currency: "EUR", cities: ["Riga", "Daugavpils", "Liepāja", "Cēsis"] },
  { name: "Lebanon", iso2: "LB", currency: "LBP", cities: ["Beirut", "Byblos", "Tripoli", "Baalbek"] },
  { name: "Lesotho", iso2: "LS", currency: "LSL", cities: ["Maseru", "Teyateyaneng", "Mafeteng"] },
  { name: "Liberia", iso2: "LR", currency: "LRD", cities: ["Monrovia", "Gbarnga", "Buchanan"] },
  { name: "Libya", iso2: "LY", currency: "LYD", cities: ["Tripoli", "Benghazi", "Misrata"] },
  { name: "Liechtenstein", iso2: "LI", currency: "CHF", cities: ["Vaduz", "Schaan", "Triesen"] },
  { name: "Lithuania", iso2: "LT", currency: "EUR", cities: ["Vilnius", "Kaunas", "Klaipėda", "Trakai"] },
  { name: "Luxembourg", iso2: "LU", currency: "EUR", cities: ["Luxembourg City", "Esch-sur-Alzette", "Echternach"] },
  { name: "Macau", iso2: "MO", currency: "MOP", cities: ["Macau", "Taipa", "Coloane"] },
  { name: "Madagascar", iso2: "MG", currency: "MGA", cities: ["Antananarivo", "Toamasina", "Mahajanga", "Nosy Be"] },
  { name: "Malawi", iso2: "MW", currency: "MWK", cities: ["Lilongwe", "Blantyre", "Mzuzu"] },
  { name: "Malaysia", iso2: "MY", currency: "MYR", cities: ["Kuala Lumpur", "Penang", "Malacca", "Kota Kinabalu", "Langkawi"] },
  { name: "Maldives", iso2: "MV", currency: "MVR", cities: ["Malé", "Addu City", "Malé Atoll"] },
  { name: "Mali", iso2: "ML", currency: "XOF", cities: ["Bamako", "Sikasso", "Ségou", "Timbuktu"] },
  { name: "Malta", iso2: "MT", currency: "EUR", cities: ["Valletta", "Sliema", "St. Julian's", "Gozo"] },
  { name: "Marshall Islands", iso2: "MH", currency: "USD", cities: ["Majuro", "Ebeye"] },
  { name: "Mauritania", iso2: "MR", currency: "MRU", cities: ["Nouakchott", "Nouadhibou", "Rosso"] },
  { name: "Mauritius", iso2: "MU", currency: "MUR", cities: ["Port Louis", "Curepipe", "Grand Baie", "Flic en Flac"] },
  { name: "Mexico", iso2: "MX", currency: "MXN", cities: ["Mexico City", "Cancún", "Guadalajara", "Oaxaca", "Tulum", "Puerto Vallarta"] },
  { name: "Micronesia", iso2: "FM", currency: "USD", cities: ["Palikir", "Weno", "Kolonia"] },
  { name: "Moldova", iso2: "MD", currency: "MDL", cities: ["Chișinău", "Tiraspol", "Bălți"] },
  { name: "Monaco", iso2: "MC", currency: "EUR", cities: ["Monaco", "Monte Carlo", "La Condamine"] },
  { name: "Mongolia", iso2: "MN", currency: "MNT", cities: ["Ulaanbaatar", "Erdenet", "Kharkhorin"] },
  { name: "Montenegro", iso2: "ME", currency: "EUR", cities: ["Podgorica", "Kotor", "Budva", "Tivat"] },
  { name: "Morocco", iso2: "MA", currency: "MAD", cities: ["Marrakech", "Casablanca", "Fes", "Chefchaouen", "Tangier"] },
  { name: "Mozambique", iso2: "MZ", currency: "MZN", cities: ["Maputo", "Beira", "Nampula", "Tofo"] },
  { name: "Myanmar", iso2: "MM", currency: "MMK", cities: ["Yangon", "Mandalay", "Bagan", "Inle Lake"] },
  { name: "Namibia", iso2: "NA", currency: "NAD", cities: ["Windhoek", "Swakopmund", "Walvis Bay"] },
  { name: "Nauru", iso2: "NR", currency: "AUD", cities: ["Yaren", "Aiwo", "Boe"] },
  { name: "Nepal", iso2: "NP", currency: "NPR", cities: ["Kathmandu", "Pokhara", "Lukla", "Chitwan"] },
  { name: "Netherlands", iso2: "NL", currency: "EUR", cities: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht"] },
  { name: "New Caledonia", iso2: "NC", currency: "XPF", cities: ["Nouméa", "Dumbéa", "Mont-Dore"] },
  { name: "New Zealand", iso2: "NZ", currency: "NZD", cities: ["Auckland", "Wellington", "Queenstown", "Christchurch", "Rotorua"] },
  { name: "Nicaragua", iso2: "NI", currency: "NIO", cities: ["Managua", "León", "Granada", "San Juan del Sur"] },
  { name: "Niger", iso2: "NE", currency: "XOF", cities: ["Niamey", "Zinder", "Maradi"] },
  { name: "Nigeria", iso2: "NG", currency: "NGN", cities: ["Lagos", "Abuja", "Kano", "Ibadan"] },
  { name: "North Korea", iso2: "KP", currency: "KPW", cities: ["Pyongyang", "Hamhung", "Chongjin"] },
  { name: "North Macedonia", iso2: "MK", currency: "MKD", cities: ["Skopje", "Ohrid", "Bitola"] },
  { name: "Norway", iso2: "NO", currency: "NOK", cities: ["Oslo", "Bergen", "Tromsø", "Stavanger"] },
  { name: "Oman", iso2: "OM", currency: "OMR", cities: ["Muscat", "Salalah", "Nizwa"] },
  { name: "Pakistan", iso2: "PK", currency: "PKR", cities: ["Karachi", "Lahore", "Islamabad", "Peshawar"] },
  { name: "Palau", iso2: "PW", currency: "USD", cities: ["Ngerulmud", "Koror", "Airai"] },
  { name: "Palestine", iso2: "PS", currency: "ILS", cities: ["Bethlehem", "Ramallah", "Gaza City", "Jericho"] },
  { name: "Panama", iso2: "PA", currency: "USD", cities: ["Panama City", "Boquete", "Bocas del Toro"] },
  { name: "Papua New Guinea", iso2: "PG", currency: "PGK", cities: ["Port Moresby", "Lae", "Mount Hagen"] },
  { name: "Paraguay", iso2: "PY", currency: "PYG", cities: ["Asunción", "Ciudad del Este", "Encarnación"] },
  { name: "Peru", iso2: "PE", currency: "PEN", cities: ["Lima", "Cusco", "Arequipa", "Machu Picchu", "Puno"] },
  { name: "Philippines", iso2: "PH", currency: "PHP", cities: ["Manila", "Cebu", "Boracay", "Palawan", "Bohol"] },
  { name: "Poland", iso2: "PL", currency: "PLN", cities: ["Warsaw", "Kraków", "Gdańsk", "Wrocław", "Zakopane"] },
  { name: "Portugal", iso2: "PT", currency: "EUR", cities: ["Lisbon", "Porto", "Faro", "Sintra", "Madeira"] },
  { name: "Puerto Rico", iso2: "PR", currency: "USD", cities: ["San Juan", "Ponce", "Mayagüez", "Vieques"] },
  { name: "Qatar", iso2: "QA", currency: "QAR", cities: ["Doha", "Al Rayyan", "Al Wakrah"] },
  { name: "Romania", iso2: "RO", currency: "RON", cities: ["Bucharest", "Cluj-Napoca", "Brașov", "Sibiu", "Transylvania"] },
  { name: "Russia", iso2: "RU", currency: "RUB", cities: ["Moscow", "St. Petersburg", "Kazan", "Vladivostok", "Sochi"] },
  { name: "Rwanda", iso2: "RW", currency: "RWF", cities: ["Kigali", "Musanze", "Huye"] },
  { name: "Saint Kitts and Nevis", iso2: "KN", currency: "XCD", cities: ["Basseterre", "Charlestown"] },
  { name: "Saint Lucia", iso2: "LC", currency: "XCD", cities: ["Castries", "Gros Islet", "Soufrière"] },
  { name: "Saint Vincent and the Grenadines", iso2: "VC", currency: "XCD", cities: ["Kingstown", "Georgetown", "Barrouallie"] },
  { name: "Samoa", iso2: "WS", currency: "WST", cities: ["Apia", "Vaitele", "Falefa"] },
  { name: "San Marino", iso2: "SM", currency: "EUR", cities: ["San Marino", "Serravalle", "Borgo Maggiore"] },
  { name: "São Tomé and Príncipe", iso2: "ST", currency: "STN", cities: ["São Tomé", "Santo António"] },
  { name: "Saudi Arabia", iso2: "SA", currency: "SAR", cities: ["Riyadh", "Jeddah", "Mecca", "Medina"] },
  { name: "Senegal", iso2: "SN", currency: "XOF", cities: ["Dakar", "Saint-Louis", "Saly"] },
  { name: "Serbia", iso2: "RS", currency: "RSD", cities: ["Belgrade", "Novi Sad", "Niš"] },
  { name: "Seychelles", iso2: "SC", currency: "SCR", cities: ["Victoria", "Anse Boileau", "Beau Vallon"] },
  { name: "Sierra Leone", iso2: "SL", currency: "SLL", cities: ["Freetown", "Bo", "Kenema"] },
  { name: "Singapore", iso2: "SG", currency: "SGD", cities: ["Singapore", "Sentosa", "Jurong"] },
  { name: "Slovakia", iso2: "SK", currency: "EUR", cities: ["Bratislava", "Košice", "High Tatras", "Banská Štiavnica"] },
  { name: "Slovenia", iso2: "SI", currency: "EUR", cities: ["Ljubljana", "Bled", "Piran", "Maribor"] },
  { name: "Solomon Islands", iso2: "SB", currency: "SBD", cities: ["Honiara", "Auki", "Gizo"] },
  { name: "Somalia", iso2: "SO", currency: "SOS", cities: ["Mogadishu", "Hargeisa", "Bosaso"] },
  { name: "South Africa", iso2: "ZA", currency: "ZAR", cities: ["Cape Town", "Johannesburg", "Durban", "Pretoria", "Kruger National Park"] },
  { name: "South Korea", iso2: "KR", currency: "KRW", cities: ["Seoul", "Busan", "Jeju", "Incheon", "Gyeongju"] },
  { name: "South Sudan", iso2: "SS", currency: "SSP", cities: ["Juba", "Wau", "Malakal"] },
  { name: "Spain", iso2: "ES", currency: "EUR", cities: ["Barcelona", "Madrid", "Seville", "Granada", "Valencia", "Ibiza", "San Sebastián"] },
  { name: "Sri Lanka", iso2: "LK", currency: "LKR", cities: ["Colombo", "Kandy", "Galle", "Sigiriya", "Ella"] },
  { name: "Sudan", iso2: "SD", currency: "SDG", cities: ["Khartoum", "Omdurman", "Port Sudan"] },
  { name: "Suriname", iso2: "SR", currency: "SRD", cities: ["Paramaribo", "Lelydorp", "Nieuw Nickerie"] },
  { name: "Sweden", iso2: "SE", currency: "SEK", cities: ["Stockholm", "Gothenburg", "Malmö", "Kiruna"] },
  { name: "Switzerland", iso2: "CH", currency: "CHF", cities: ["Zurich", "Geneva", "Lucerne", "Interlaken", "Zermatt"] },
  { name: "Syria", iso2: "SY", currency: "SYP", cities: ["Damascus", "Aleppo", "Homs", "Palmyra"] },
  { name: "Taiwan", iso2: "TW", currency: "TWD", cities: ["Taipei", "Kaohsiung", "Tainan", "Taroko Gorge"] },
  { name: "Tajikistan", iso2: "TJ", currency: "TJS", cities: ["Dushanbe", "Khujand", "Khorugh"] },
  { name: "Tanzania", iso2: "TZ", currency: "TZS", cities: ["Dar es Salaam", "Zanzibar", "Arusha", "Serengeti", "Kilimanjaro"] },
  { name: "Thailand", iso2: "TH", currency: "THB", cities: ["Bangkok", "Chiang Mai", "Phuket", "Krabi", "Pattaya", "Chiang Rai"] },
  { name: "Timor-Leste", iso2: "TL", currency: "USD", cities: ["Dili", "Baucau", "Maliana"] },
  { name: "Togo", iso2: "TG", currency: "XOF", cities: ["Lomé", "Sokodé", "Kara"] },
  { name: "Tonga", iso2: "TO", currency: "TOP", cities: ["Nuku'alofa", "Neiafu", "Haveluloto"] },
  { name: "Trinidad and Tobago", iso2: "TT", currency: "TTD", cities: ["Port of Spain", "San Fernando", "Scarborough"] },
  { name: "Tunisia", iso2: "TN", currency: "TND", cities: ["Tunis", "Sfax", "Sousse", "Djerba"] },
  { name: "Turkey", iso2: "TR", currency: "TRY", cities: ["Istanbul", "Cappadocia", "Antalya", "Izmir", "Bodrum"] },
  { name: "Turkmenistan", iso2: "TM", currency: "TMT", cities: ["Ashgabat", "Turkmenabat", "Mary"] },
  { name: "Tuvalu", iso2: "TV", currency: "AUD", cities: ["Funafuti", "Fongafale"] },
  { name: "Uganda", iso2: "UG", currency: "UGX", cities: ["Kampala", "Entebbe", "Jinja"] },
  { name: "Ukraine", iso2: "UA", currency: "UAH", cities: ["Kyiv", "Lviv", "Odessa", "Kharkiv"] },
  { name: "United Arab Emirates", iso2: "AE", currency: "AED", cities: ["Dubai", "Abu Dhabi", "Sharjah"] },
  { name: "United Kingdom", iso2: "GB", currency: "GBP", cities: ["London", "Edinburgh", "Manchester", "Liverpool", "Bath", "Oxford"] },
  { name: "United States", iso2: "US", currency: "USD", cities: ["New York", "Los Angeles", "San Francisco", "Chicago", "Las Vegas", "Miami", "Seattle", "Boston", "Washington D.C.", "Austin", "Denver", "New Orleans", "Portland", "San Diego", "Honolulu"] },
  { name: "Uruguay", iso2: "UY", currency: "UYU", cities: ["Montevideo", "Punta del Este", "Colonia del Sacramento"] },
  { name: "Uzbekistan", iso2: "UZ", currency: "UZS", cities: ["Tashkent", "Samarkand", "Bukhara", "Khiva"] },
  { name: "Vanuatu", iso2: "VU", currency: "VUV", cities: ["Port Vila", "Luganville", "Norsup"] },
  { name: "Vatican City", iso2: "VA", currency: "EUR", cities: ["Vatican City"] },
  { name: "Venezuela", iso2: "VE", currency: "VES", cities: ["Caracas", "Maracaibo", "Valencia", "Mérida"] },
  { name: "Vietnam", iso2: "VN", currency: "VND", cities: ["Hanoi", "Ho Chi Minh City", "Hoi An", "Halong Bay", "Da Nang", "Sapa"] },
  { name: "Yemen", iso2: "YE", currency: "YER", cities: ["Sana'a", "Aden", "Taiz"] },
  { name: "Zambia", iso2: "ZM", currency: "ZMW", cities: ["Lusaka", "Livingstone", "Ndola"] },
  { name: "Zimbabwe", iso2: "ZW", currency: "ZWL", cities: ["Harare", "Bulawayo", "Victoria Falls"] },
];

// Derived: alphabetical list of country names (for the selector).
export const COUNTRIES: string[] = COUNTRY_DATA.map((c) => c.name).sort((a, b) => a.localeCompare(b));

// Derived: country name → ISO currency code.
export const COUNTRY_CURRENCY: Record<string, string> = Object.fromEntries(
  COUNTRY_DATA.map((c) => [c.name, c.currency])
);

// Derived: every city across all countries, sorted + de-duplicated (for autocomplete).
export const ALL_CITIES: string[] = Array.from(
  new Set(COUNTRY_DATA.flatMap((c) => c.cities))
).sort((a, b) => a.localeCompare(b));

/** Returns the ISO currency code for a country (defaults to USD). */
export function currencyForCountry(country: string): string {
  return COUNTRY_CURRENCY[country] ?? "USD";
}

/** Returns the major cities for a country (empty if unknown). */
export function citiesForCountry(country: string): string[] {
  return COUNTRY_DATA.find((c) => c.name === country)?.cities ?? [];
}
