import type { Metadata } from "next";
import Link from "next/link";

const SITE_URL = "https://trip-planify.vercel.app";
const PAGE_URL = `${SITE_URL}/disclaimer`;

export const metadata: Metadata = {
  title: "Disclaimer",
  description:
    "Trip Planify generates AI-powered itineraries. Plans may contain inaccurate prices, timings, or availability — always verify independently before booking.",
  alternates: { canonical: PAGE_URL },
  keywords: [
    "Trip Planify disclaimer",
    "AI travel planner disclaimer",
    "travel planning disclaimer",
    "AI itinerary accuracy",
    "trip planner liability",
  ],
  openGraph: {
    title: "Disclaimer | Trip Planify",
    description:
      "Trip Planify generates AI-powered itineraries. Plans may contain inaccurate prices, timings, or availability — always verify independently before booking.",
    url: PAGE_URL,
    type: "website",
    siteName: "Trip Planify",
    locale: "en_US",
  },
  twitter: {
    card: "summary",
    title: "Disclaimer | Trip Planify",
    description:
      "Trip Planify generates AI-powered itineraries. Plans may contain inaccurate prices, timings, or availability — always verify independently before booking.",
  },
};

export default function DisclaimerPage() {
  return (
    <main className="travel-bg min-h-screen">
      <article className="max-w-3xl mx-auto px-4 py-10 sm:py-14">
        <Link
          href="/"
          className="inline-flex items-center text-sm font-medium text-primary hover:underline mb-8"
        >
          ← Back to home
        </Link>

        <h1 className="font-display text-2xl sm:text-3xl font-bold mb-2 text-foreground">
          Disclaimer
        </h1>
        <p className="text-sm text-muted-foreground mb-10">
          Last Updated: July 2025
        </p>

        <div className="space-y-8 text-foreground/80 leading-relaxed">
          <p>
            Trip Planify is an AI-powered travel planning tool intended to help
            you quickly draft trip ideas. The information below explains the
            limits of what the tool can provide and your responsibilities as a
            user.
          </p>

          <section>
            <h2 className="font-display text-xl sm:text-2xl font-semibold mb-3 text-foreground">
              AI-Generated Content
            </h2>
            <p>
              All itineraries produced by Trip Planify are generated by an
              artificial intelligence model and may contain inaccuracies.
              Prices, timings, opening hours, availability, transportation
              schedules, and other details should be independently verified
              with the relevant service provider before you make any booking or
              travel decision. Treat generated plans as a helpful starting
              point, not as a definitive source of truth.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl sm:text-2xl font-semibold mb-3 text-foreground">
              No Guarantee of Accuracy
            </h2>
            <p>
              We do not guarantee the accuracy, completeness, timeliness, or
              reliability of any generated plan. Attraction names, hotel
              suggestions, restaurant recommendations, distance and travel-time
              estimates, and cost figures are AI approximations based on the
              model&rsquo;s general training knowledge — not on real-time data,
              live prices, or current availability. Real-world conditions can
              differ significantly from what appears in your plan.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl sm:text-2xl font-semibold mb-3 text-foreground">
              Not a Booking Platform
            </h2>
            <p>
              Trip Planify is a planning tool, not a booking platform. We do
              not handle reservations, payments, ticketing, or any other
              booking transaction. Any bookings you make based on a generated
              plan — for flights, hotels, activities, transportation, or
              anything else — are made directly between you and the relevant
              third-party provider, and are solely your responsibility. Always
              confirm pricing, terms, and cancellation policies with the
              provider before paying.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl sm:text-2xl font-semibold mb-3 text-foreground">
              Travel Risks
            </h2>
            <p>
              Travel involves inherent risks. Before traveling, always check
              current travel advisories issued by your government, visa and
              passport requirements for your destination, vaccination and
              health guidance, weather conditions, local customs, and safety
              information. Trip Planify does not assess or guarantee the safety
              of any destination, route, or activity suggested in a generated
              plan. You are responsible for evaluating whether a trip is
              appropriate for your circumstances.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl sm:text-2xl font-semibold mb-3 text-foreground">
              Third-Party Content
            </h2>
            <p>
              Place images shown in your generated plan are sourced from
              Wikipedia and Wikimedia Commons contributors. We do not verify the
              accuracy of these images or any associated third-party content,
              and we are not responsible for the accuracy, licensing, or
              appropriateness of third-party material. All third-party
              trademarks, names, and content remain the property of their
              respective owners.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl sm:text-2xl font-semibold mb-3 text-foreground">
              Limitation of Liability
            </h2>
            <p>
              To the fullest extent permitted by applicable law, Trip Planify
              and its creators, operators, and contributors are not liable for
              any losses, damages, costs, or inconveniences arising from your
              use of generated plans. This includes, without limitation, direct
              or indirect damages resulting from booking errors, price
              discrepancies, missed reservations, inaccurate travel times,
              unavailable attractions, travel disruptions, or any other outcome
              related to reliance on AI-generated content. Your use of the
              service is at your own risk.
            </p>
          </section>

          <section>
            <h2 className="font-display text-xl sm:text-2xl font-semibold mb-3 text-foreground">
              Use at Your Own Risk
            </h2>
            <p>
              By using Trip Planify, you acknowledge that generated plans are
              provided for informational and inspirational purposes only, and
              that you agree to verify all details — prices, timings,
              availability, safety, and legal requirements — independently
              before making any travel decision. If you do not agree with this
              disclaimer, please do not use the service. For any questions,
              reach us at{" "}
              <a
                href="mailto:tripplanify.app@gmail.com"
                className="text-primary hover:underline"
              >
                tripplanify.app@gmail.com
              </a>{" "}
              or through our{" "}
              <Link href="/contact" className="text-primary hover:underline">
                contact page
              </Link>
              .
            </p>
          </section>
        </div>
      </article>
    </main>
  );
}
